# Generated by Django 3.2 on 2021-04-13 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_plan',
            field=models.CharField(default=None, max_length=128),
        ),
    ]
